apiVersion: v1
kind: Service
metadata:
  name: voting-app
  labels:
    name: voting-app-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    name: voting-app-pod
